name: Scrape HubSpot Blog (Playwright)

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run-playwright-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install gspread oauth2client playwright
        playwright install chromium

    - name: Criar credenciais.json a partir do secret codificado
      run: echo "${{ secrets.GSHEETS_KEY_B64 }}" | base64 -d > credenciais.json

    - name: Executar o scraper com Playwright
      run: python processar_prompts.py
