name: Processar Prompts com OpenAI

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  gerar-prompts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install gspread oauth2client openai

    - name: Criar credenciais.json a partir do secret codificado
      run: echo "${{ secrets.GSHEETS_KEY_B64 }}" | base64 -d > credenciais.json

    - name: Executar o script que gera os posts
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python processar_prompts.py
